models:
  - name: stg_coins
    columns:
      - name: coin_id
        tests:
          - not_null
          - unique
      - name: price_usd
        tests:
          - not_null

  - name: mart_coin_performance
    columns:
      - name: coin_id
        tests:
         - not_null
          - unique
      - name: market_cap_usd
        tests:
          - unique
          - not_null
          
          
