version: 2

sources:
  - name: raw
    database: CRYPTO_DB
    schema: ANALYTICS
    tables:
      - name: raw_coingecko_markets
      - name: raw_fear_greed_index
      - name: raw_exchange_rates
      - name: raw_global_market